name: Push to master

on:
  push:
    branches:
      - master

jobs:
  labels:
    name: Update repo labels
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download labels' config
        shell: bash
        run: |
          mkdir -p .tmp
          curl -LsS https://raw.githubusercontent.com/devops-infra/.github/master/.github/labels.yml -o .tmp/labels.yml

      - name: Update labels
        uses: crazy-max/ghaction-github-labeler@v4.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .tmp/labels.yml

  lint:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Haskell Dockerfile Linter (Hadolint)
        uses: brpaz/hadolint-action@v1.5.0
        with:
          dockerfile: Dockerfile

  build_and_push:
    name: Build and push images in parallel
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        flavour: [slim, plain, aws, azure, gcp, aws-azure, aws-gcp, azure-gcp, aws-azure-gcp]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1
        with:
          install: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
        with:
          image: tonistiigi/binfmt:latest
          platforms: amd64,arm64

      - name: Build Docker image and push to registry
        env:
          DOCKER_BUILDKIT: 1
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TERM: xterm-256color
        run: make push-${{ matrix.flavour }}
